### PR TITLE
Improve general styling

### LINKED ISSUE #39: Improve Styling of Whole Page
- [x] Find background
- [x] Find logo
- [x] Change grid to look like mock up
- [x] Make Fresh Logo and Map not move, make it sticky
- [x] Make FAB not move, make it sticky (because the page will not scroll)
- [x] Make page not scroll

### LINKED ISSUE #40: Improve CardList
- [x] Make search bar thinner
- [x] Style 'sort by price / sort by latest' 
* Suggestions: https://material-ui.com/components/toggle-button/, https://material-ui.com/components/buttons/#buttons
- [x] Make find item search bar and sort, both sticky at the top
- [x] Make list of cards scrollable
- [x] Add spacing between cards

### PR DESCRIPTION
**Pull request by nicolehli**
* Add background
* Add logo
* Change grid to look like the design mock up
*  Make these sticky
-- Logo
-- Map
-- FAB
-- Search
-- Sort buttons 
* Page no longer scrolls
* Card List does scroll
* FAB icon updated to "+ Fresh Deal"

Screen Shot 2019-07-04 at 8 42 05 PM

Closes #39 
Closes #40

### CODE REVIEW

**Comment by YaoLiu93** [comment]
Speaking of which, we should also update our colour schemes. That's something we forgot to mention. I'm thinking the FAB should be a similar green to the sort button. In addition to our submit button on our freshform!

**Comment by inquisitiv-e** [comment]
Also I think our FAB should say "New Post" later because the plus sign isn't super clear on what it wants users to do.

**Comment by YaoLiu93** [comment]
https://material-ui.com/components/buttons/#floating-action-buttons
Make... `+ Fresh Post? `

**Comment by nicolehli** [comment]
image 

??

image

**Comment by nicolehli** [comment]
I kind of like the red FAB color. Pops.

**Comment by YaoLiu93** [comment]
True. Red does look decent.

Looking the at material design, extended fab can do with or without an icon. But if we add the +, maybe we want it to be an icon and not part of the string +?

**Comment by nicolehli** [comment]
> True. Red does look decent.
> 
> Looking the at material design, extended fab can do with or without an icon. But if we add the +, maybe we want it to be an icon and not part of the string +?

1
image

2
image

**Comment by YaoLiu93** [comment]
1 all the way.

Erica thoughts?

**Comment by inquisitiv-e** [comment]
I like the red better as well :)

**Comment by nicolehli** [comment]
k red or green.  should i make the price sort red too? 

Screen Shot 2019-07-04 at 8 34 08 PM

Screen Shot 2019-07-04 at 8 36 28 PM

Screen Shot 2019-07-04 at 8 32 56 PM

**Comment by inquisitiv-e** [comment]
> k red or green. should i make the price sort red too?
> 
> Screen Shot 2019-07-04 at 8 34 08 PM
> 
> Screen Shot 2019-07-04 at 8 36 28 PM
> 
> Screen Shot 2019-07-04 at 8 32 56 PM

I think green looks better for sort!

**Comment by nicolehli** [comment]
Updated FAB to be extended and say + FRESH DEAL for now. Plus is an icon.

**Comment by YaoLiu93** [comment]
Green sorting + Red Button is WIN WIN WIN

**Pull request merged**
