### PR TITLE
Add state to thumbs up and down rating

### PR DESCRIPTION
**Pull request by nicolehli**
This PR is to add restrictions to hitting thumbs up/down many many times. Note, public user refreshing page can add another rating. 

- Add logic to turn outline to solid thumb
- Add logic to undo a solid from opposite thumb
- Add logic to undo a solid from the same thumb

Jul-27-2019 23-50-45

### CODE REVIEW

**Comment by YaoLiu93** [comment]
> Note, public user refreshing page can add another rating.

If that's the case, do we want to remove the ability for public users to vote altogether?

**Comment by YaoLiu93** [comment]
Otherwise, changes look fine.

**Comment by nicolehli** [comment]
@YaoLiu93 we talked about it last last workshop and I rmb we said if public can't see thumbs, the floating number (rating) would look silly. I think rating and report deals could be for public, and it would be okay. signed in is more for shopping list really imo.

**Comment by YaoLiu93** [comment]
You can see thumbs, just disabled (so greyed out) or not clickable.

**Comment by nicolehli** [comment]
@YaoLiu93 CMIIW, it's not that simple moving rating functionality from public to private... because in short, all our login-able users now have their own thumbs state for each card. 

When users login, all these states need to show up for a user (user 1 - thumbs up solid on card 1, thumbs down on card 2 etc...  but user 2 have entirely different thumb states... user 100 have some thumb states). We need to have a new data structure to store users/thumbs/cards relationships, or user what we have such as cards database knowing which user to what thumbs states, or users database knowing what cards have what thumbs states... am I overthinking?

The shopping list is the tracking mechanism on what card items are added for a user who's logged in. But for rating thumb states, the mechanism will require some more work right...

**Comment by YaoLiu93** [comment]
Ahhhh whoops. I misunderstood your changes. Yes you're right, there would be substantial effort to have user ratings tracked per card.

The logic you've added was only the transition between the different thumb states and rating counts for the given page, not stored per user.

**Pull request merged**
